---
# tasks file for iptables

- name: "iptables: REJECT invalid packets"
  iptables:
    chain: INPUT
    ctstate: INVALID
    jump: REJECT
    comment: REJECT invalid packets
  register: iptables_invalid

- name: "iptables: Allow all loopback traffic"
  iptables:
    chain: "{{ item }}"
    source: 127.0.0.1/8
    jump: ACCEPT
    comment: Allow all loopback traffic
  with_items:
    - INPUT
    - OUTPUT
    - FORWARD
  register: iptables_loopback

- name: "iptables: Allow related and established connections"
  iptables:
    chain: "{{ item }}"
    ctstate: ESTABLISHED,RELATED
    jump: ACCEPT
    comment: Allow related and established connections
  with_items:
    - INPUT
    - OUTPUT
    - FORWARD
  register: iptables_related_established

- name: "iptables: Allow dns requests"
  iptables:
    chain: OUTPUT
    protocol: udp
    destination_port: 53
    ctstate: NEW,ESTABLISHED
    jump: ACCEPT
    comment: Allow outgoing dns requests
  register: iptables_dns

- name: "iptables: Allow outgoing connections to http[s]"
  iptables:
    chain: OUTPUT
    protocol: tcp
    destination_port: "{{ item }}"
    ctstate: NEW,ESTABLISHED
    jump: ACCEPT
    comment: Allow outgoing connections to web
  with_items:
    - 80
    - 443
  register: iptables_out_http

- name: "iptables: Allow icmp"
  iptables:
    chain: "{{ item }}"
    protocol: icmp
    jump: ACCEPT
    comment: "Allow icmp"
  with_items:
    - INPUT
    - OUTPUT
    - FORWARD
  register: iptables_icmp

- name: "iptables: Policy -> DROP"
  iptables:
    chain: "{{ item }}"
    policy: DROP
  with_items:
    - INPUT
    - OUTPUT
    - FORWARD
  register: iptables_policy

- name: Save rulles
  shell: /sbin/iptables-save > /etc/network/iptables.up.rules
  changed_when: iptables_invalid is changed or iptables_loopback is changed or iptables_related_established is changed or iptables_dns is changed or iptables_out_http is changed or iptables_icmp is changed or iptables_policy is changed

- name: Auto-restore iptables on boot
  lineinfile:
    path: /etc/network/interfaces
    regexp: '^post-up.*'
    insertafter: '^iface lo inet loopback'
    line: 'post-up /sbin/iptables-restore /etc/network/iptables.up.rules'


